### ISSUE TITLE
Incorrect name parsing when contains trailing space

### ISSUE THREAD

**Issue by robertandrews** [ADCI/full-name-parser#6] opened 2018-03-01 12:04 UTC
Hi,
I am having real problems getting this to work inside WPAllImport, a WordPress plugin that imports CSV content in as User data.

WPAllImport works by me creating a template wherein input data maps to WordPress field data, eg. "first_name", "last_name" and a custom field named "name_mid").

But it also allows passing of input data to functions to allow processing of that data during import, before save.

My source name is field "name_full" (eg. Jokubas Phillip Gardner).

In the WPAllImport template, I am calling my function `get_name_part` in the first-, middle- and last-name fields like this...

```
[get_name_part({name_full[1]}, "first")]
[get_name_part({name_full[1]}, "middle")]
[get_name_part({name_full[1]}, "last")]
```

My function `get_name_part` should then take both the full source name and a string corresponding to your 'part' options...

Essentially, a single function should be able to return whichever part is specified, rather than write a separate function for each...

```
  require_once '/home/mysite/public_html/wp-content/plugins/cxt-user-wpai-import/full-name-parser/vendor/autoload.php';

  use ADCI\FullNameParser\Parser;

  // name eg. Jokūbas Phillip Gardner
  // part eg. title, first, middle, last, nick, suffix,
  // called via eg. [get_name_part({name_full[1]}, "first")]
  function get_name_part($name, $part) {

    $parser = new Parser(
      [
        'part' => $part,
        // 'fix_case' => FALSE,
        'throws' => FALSE
      ]
    );

    // Return the parsed name part
    $nameObject = $parser->parse($name);

    // Give it back to WPAllImport
    return $nameObject;

  }

```

The problem is...

1. The first operation completes successfully. That is, putting [get_name_part({name_full[1]}, "first")] in my import settings' first_name field successfully saves a parsed first name (eg. "Jokubas") in the first_name WordPress field.

2. However, things break down after that. [get_name_part({name_full[1]}, "last")] places no name at all in the last_name field. It repeatedly fails.

3. And [get_name_part({name_full[1]}, "middle")] places an incorrect combination of the actual middle and last (eg. "Phillip Gardner") as middle name.

So the ultimate split is:

- First: Jokubas
- Middle: Phillip Gardner
- Last: [blank]

This is not consistent with full-name-parser, which correctly parses outside of my function and import environment...

- First: Jokubas
- Middle: Phillip
- Last: Gardner

I'm not sure what the reason is, but I feel like it may be something to do with calling the same function three times from the same import step, albeit with different parameters.

I thought about the need to destroy all variables at the end of the function, but "unset" on `$name`, `$part`, `$parser` or `$nameObject` does not fix anything.

Please could you assist?

Thanks.

**Comment by gennadiylitvinyuk** [comment] 2018-03-02 09:16
It is caused by trailing space in input  like `'Jokubas Phillip Gardner '`

You can fix it by trimming input with `trim()`

**Comment by Deyter** [comment] 2018-03-02 10:35
@gennadiylitvinyuk 
Thanks for your help. It will be fixed nearest time.

**Comment by gennadiylitvinyuk** [comment] 2018-03-02 10:44
There is a pull request, which fixes this

**Comment by robertandrews** [comment] 2018-03-02 13:47
Noting this with thanks. I had not noticed my trailing spaces. `trim` is the solution. Thanks for fixing.

**Closed as completed** 2018-03-05 02:36 UTC
Labels: bug
